### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by rpatel99** [travishathaway/python-ach#30]
Hey, I am trying to install python-ach library using `pip install python-ach`. I am getting the following error for `charmap`. Please advice.

```ERROR: Command errored out with exit status 1:
     command: 'c:\users\romyp\desktop\stins projects\eft-fixer\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\romyp\\AppData\\Local\\Temp\\pip-install-6cqtbijg\\ach\\setup.py'"'"'; __file__='"'"'C:\\Users\\romyp\\AppData\\Local\\Temp\\pip-install-6cqtbijg\\ach\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\romyp\AppData\Local\Temp\pip-install-6cqtbijg\ach\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\romyp\AppData\Local\Temp\pip-install-6cqtbijg\ach\setup.py", line 14, in <module>
        long_description=open('README.rst').read(),
      File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 242: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by rpatel99** [comment]
Nvm, it's fixed now.
